#!/usr/bin/env python3

import argparse
from pathlib import Path


def main() -> None:
    parser = argparse.ArgumentParser(
        description=(
            "Parse a chain generated by bcftools consensus. "
            "The target sequence is A/reference and the query sequence is C/consensus."
        )
    )
    parser.add_argument("chain", help="Chain generated by bcftools consensus -c")
    parser.add_argument("prefix", help="Output prefix, for example A_C")
    args = parser.parse_args()

    prefix = Path(args.prefix)

    blocks_path = Path(f"{prefix}.backbone_blocks.tsv")
    insertions_path = Path(f"{prefix}.insertions_on_C.tsv")
    deletions_path = Path(f"{prefix}.deletions_on_A.tsv")
    complex_path = Path(f"{prefix}.complex_replacements.tsv")

    with (
        open(args.chain, encoding="utf-8") as chain_file,
        open(blocks_path, "w", encoding="utf-8") as blocks,
        open(insertions_path, "w", encoding="utf-8") as insertions,
        open(deletions_path, "w", encoding="utf-8") as deletions,
        open(complex_path, "w", encoding="utf-8") as complex_out,
    ):
        blocks.write(
            "A_chr\tA_start\tA_end\t"
            "C_chr\tC_start\tC_end\t"
            "length\tchain_id\n"
        )

        insertions.write(
            "C_chr\tC_start\tC_end\tevent_id\t"
            "A_chr\tA_anchor\tinserted_length\tchain_id\n"
        )

        deletions.write(
            "A_chr\tA_start\tA_end\tevent_id\t"
            "C_chr\tC_anchor\tdeleted_length\tchain_id\n"
        )

        complex_out.write(
            "A_chr\tA_start\tA_end\t"
            "C_chr\tC_start\tC_end\t"
            "A_gap_length\tC_gap_length\t"
            "event_id\tchain_id\n"
        )

        lines = iter(chain_file)
        event_number = 0

        for raw_line in lines:
            line = raw_line.strip()

            if not line:
                continue

            if not line.startswith("chain "):
                raise ValueError(
                    f"Unexpected line outside a chain block: {line}"
                )

            fields = line.split()

            if len(fields) != 13:
                raise ValueError(f"Malformed chain header: {line}")

            (
                _,
                _score,
                a_chr,
                _a_size,
                a_strand,
                a_start,
                _a_end,
                c_chr,
                _c_size,
                c_strand,
                c_start,
                _c_end,
                chain_id,
            ) = fields

            if a_strand != "+" or c_strand != "+":
                raise ValueError(
                    "This script expects the plus/plus chains "
                    "generated by bcftools consensus."
                )

            a_position = int(a_start)
            c_position = int(c_start)

            for raw_block in lines:
                block_line = raw_block.strip()

                if not block_line:
                    break

                values = block_line.split()

                if len(values) not in (1, 3):
                    raise ValueError(
                        f"Malformed chain alignment line: {block_line}"
                    )

                block_size = int(values[0])

                # Ungapped A-derived backbone block.
                if block_size > 0:
                    blocks.write(
                        f"{a_chr}\t{a_position}\t"
                        f"{a_position + block_size}\t"
                        f"{c_chr}\t{c_position}\t"
                        f"{c_position + block_size}\t"
                        f"{block_size}\t{chain_id}\n"
                    )

                a_position += block_size
                c_position += block_size

                # Last alignment block contains only block_size.
                if len(values) == 1:
                    break

                # dt: gap in target/reference A.
                # dq: gap in query/consensus C.
                dt = int(values[1])
                dq = int(values[2])

                event_number += 1
                event_id = f"CHAIN_EVENT_{event_number:08d}"

                if dt == 0 and dq > 0:
                    # Sequence exists in C but not in A:
                    # insertion in B/C relative to A.
                    insertions.write(
                        f"{c_chr}\t{c_position}\t"
                        f"{c_position + dq}\t"
                        f"{event_id}\t"
                        f"{a_chr}\t{a_position}\t"
                        f"{dq}\t{chain_id}\n"
                    )

                elif dt > 0 and dq == 0:
                    # Sequence exists in A but not in C:
                    # deletion in B/C relative to A.
                    deletions.write(
                        f"{a_chr}\t{a_position}\t"
                        f"{a_position + dt}\t"
                        f"{event_id}\t"
                        f"{c_chr}\t{c_position}\t"
                        f"{dt}\t{chain_id}\n"
                    )

                elif dt > 0 and dq > 0:
                    # Complex replacement:
                    # unaligned sequence exists on both A and C.
                    complex_out.write(
                        f"{a_chr}\t{a_position}\t"
                        f"{a_position + dt}\t"
                        f"{c_chr}\t{c_position}\t"
                        f"{c_position + dq}\t"
                        f"{dt}\t{dq}\t"
                        f"{event_id}\t{chain_id}\n"
                    )

                a_position += dt
                c_position += dq

    print(f"Wrote: {blocks_path}")
    print(f"Wrote: {insertions_path}")
    print(f"Wrote: {deletions_path}")
    print(f"Wrote: {complex_path}")


if __name__ == "__main__":
    main()